### ISSUE TITLE
CanvasToTempFilePath首次生成文件为空

### ISSUE THREAD

**Issue by xtong** [IFmiss/wx-cropper#1]
第一次执行“生成图片”总是无法预览，debug发现首次生成文件为空。
将preview移到complete中可以解决这个问题：
wx.canvasToTempFilePath({
          x: canvasL,
          y: canvasT,
          width: canvasW,
          height: canvasH,
          destWidth: canvasW,
          destHeight: canvasH,
          canvasId: 'myCanvas',
          complete: function() {
            wx.previewImage({
              current: '', // 当前显示图片的http链接
              urls: [res.tempFilePath] // 需要预览的图片http链接列表
            })
            
          }
        })

**Comment by IFmiss** [comment]
complete   api上说了是接口调用结束的回调函数（调用成功、失败都会执行）的意思，我当时在测试的时候用的两台机器一个ios一个安卓，在success中第一次是可以获取的，console的结果也是对的，我现在没有这个环境测试，你是真机测试的吗？success回调中第一次没有获取到地址吗？
