### ISSUE TITLE
v2 版本需要帮忙吗？我也许可以帮忙

### ISSUE THREAD

**Issue by 1c7** [IFmiss/wx-cropper#13]
![image](https://user-images.githubusercontent.com/1804755/50420249-54963400-0870-11e9-8051-c4b97a28624f.png)
不知道你说的"部分问题"指什么

**Comment by 1c7** [comment]
v2 比 Master branch 流畅很多，我不知道你怎么做的，我还没很仔细的看代码。
我一开始以为是 touchmove 的时候 setData 太频繁导致了卡。

看了下 v2 的 diff ，改了蛮多东西
![image](https://user-images.githubusercontent.com/1804755/50420436-7cd26280-0871-11e9-87f0-2b50c145054e.png)

**Comment by IFmiss** [comment]
可以互相学习，一起采坑

**Comment by 1c7** [comment]
快乐的一起踩坑。好的。
我先用着 v2 到实际项目里，如果踩坑摔着了回来说

**Comment by 1c7** [comment]
issue 我先关啦~
