### ISSUE TITLE
请问这个怎么移植到wepy使用呀?

### ISSUE THREAD

**Issue by Strong-Man** [IFmiss/wx-cropper#14]

**Comment by xywai1993** [comment]
首先感谢一下作者。

正好我用的是mpvue 框架，于是我fork了一份，把作者的插件翻译成 vue组件了，wepy应该也是可以用的。具体你可以看 https://github.com/xywai1993/wx-cropper  。

我在想要不要pull request 。应该大多数人用框架写小程序把。

**Comment by IFmiss** [comment]
好像也挺不错的，感谢大佬， 以后想着这个东西得再优化一下，然后抽象成组件的形式

**Comment by Strong-Man** [comment]
感谢感谢~!
