### ISSUE TITLE
v2 分支在某些 iOS 机型下(6s / 7 plus) 有裁剪出来只有一小部分的问题

### ISSUE THREAD

**Issue by 1c7** [IFmiss/wx-cropper#16]
### 期望行为
裁剪正常，和预览时的框框一致

### 实际行为
![bug](https://user-images.githubusercontent.com/1804755/52035304-2b4e7f00-2565-11e9-8870-aa05da36c64f.jpeg)
![bug2](https://user-images.githubusercontent.com/1804755/52035303-2b4e7f00-2565-11e9-90f7-95230b879983.jpeg)

### 如何复现
* OnePlus 6T 无法复现
* iPhoneX 无法复现

拿这俩测试纯粹是因为公司里只有这俩

### 问题机型
* iPhone 6S 
* iPhone 7 Plus 

这俩机型是用户告诉我们的

### 问题出现频率
偶尔出现，解决方法是关了小程序再开

### 用户的操作步骤
选择多张图片，选择不同的裁剪比例（裁剪框我控制成了无法放大缩小）
移动裁剪框。裁剪。

### 调试过程
安卓 OnePlus 6T 尝试类似步骤，无法复现。
iPhoneX 无法复现。
Testing 云测使用 iPhone 6S 无法复现
Testing 云测使用 iPhone 7 Plus 无法复现

### 问题
请问作者有没有思路这**可能**是什么问题，如何进一步定位。
或者只能是 ┑(￣Д ￣)┍ 了

**Comment by 1c7** [comment]
对于这种无法 100% 复现，只是偶尔出现的问题。我也是很头疼。如果作者没什么思路我就关掉 issue 了

**Comment by IFmiss** [comment]
@1c7 你复现过这种情况吗？ 有没有可以跑的线上版本或者体验版，裁剪出问题的话基本是在裁剪的时候获取的位置问题，或者裁剪渲染的问题，得花时间调试

**Comment by 1c7** [comment]
刚刚成功复现问题。

## 机型
iPhone 6S


## 图片情况如下：
![151548920726_ pic](https://user-images.githubusercontent.com/1804755/52039399-6190fc00-256f-11e9-9561-0997fe7fd26b.jpg)
![wechatimg16](https://user-images.githubusercontent.com/1804755/52039431-779ebc80-256f-11e9-8d4f-eaa81eb5346c.jpeg)


## 裁剪比例 3:4
![181548920927_ pic](https://user-images.githubusercontent.com/1804755/52039519-b765a400-256f-11e9-859f-cac9a60e47e3.jpg)

## iPhone 6S 结果如下
![171548920763_ pic](https://user-images.githubusercontent.com/1804755/52039551-c9474700-256f-11e9-9674-1e5cbc4cdc21.jpg)

### 用 OnePlus 6T 试图重现
安卓下没能重现，是正常的
![191548921002_ pic](https://user-images.githubusercontent.com/1804755/52039589-e11ecb00-256f-11e9-9656-121ea007bcef.jpg)


### 是否 iPhone 6S 下每次都有这样的效果？
只试了第一次就有这样的问题，我还没尝试多次是否100%复现。我去试试。

我的思路是用开发者工具看一下图片地址（我用的是七牛云存储）
如果七牛图片本身就是坏的，那就是裁剪步骤出了问题。
如果图片没坏，但是显示是这样，那就是我的代码问题。

开发者工具掉链子
![image](https://user-images.githubusercontent.com/1804755/52039713-365adc80-2570-11e9-8625-d27506dbb70f.png)

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/52039992-08c26300-2571-11e9-8118-19a8b6d174bf.png)
不清楚为什么微信开发者工具总是这样… 重启过了，版本也是最新的
(就是吐槽一下而已）

**Comment by IFmiss** [comment]
你这个比例是自己设置的是吗？  你那个比例是点击自动设置宽高的？我只能找个手机试试了

**Comment by 1c7** [comment]
我去想办法把这一整个页面抽取出来，单独拿出来。然后方便其他人测试复现。

**Comment by IFmiss** [comment]
好的 !

**Comment by 1c7** [comment]
目前此问题暂未解决，但是我先关掉这个 issue。
关掉的原因是现在的项目重点不在这里了，这个功能没删，还在。但是先不管这个小问题了。
先忙别的功能。

等我之后（也许）有空的时候，回头再来弄这个的时候。
再来 reopen 然后更新进展。

谢作者开源和前面楼层里热心回复！
