### ISSUE TITLE
点击生成图片  回报这种错

### ISSUE THREAD

**Issue by YanYaoHui** [IFmiss/wx-cropper#2]
![2017-12-19_110657](https://user-images.githubusercontent.com/29390842/34138989-4211a838-e4ad-11e7-8068-10ce449a0c40.png)
点击生成图片  回报这种错

**Comment by IFmiss** [comment]
您好  可以截一个完整的图片吗？  这个报错是在多少行出现的问题，这个应该是提示一个变量为null的值是不存在0的这个属性的，可能需要给他加一个默认值

**Comment by YanYaoHui** [comment]
![Uploading 1)GEZ`Y2`@ZTYJ~T(8CFKRH.png…]()
![Uploading )0C4F@2O~FPYQS`%)MPK_D7.png…]()

**Comment by YanYaoHui** [comment]
![1 gez y2 ztyj t 8cfkrh](https://user-images.githubusercontent.com/29390842/34139989-baf24186-e4b2-11e7-8164-f6d4bd90193f.png)
![0c4f 2o fpyqs mpk_d7](https://user-images.githubusercontent.com/29390842/34139996-c177655e-e4b2-11e7-99d3-a0cc9a1a4afa.png)
![9 9zq5 2 41kinox3dabp](https://user-images.githubusercontent.com/29390842/34140002-c76e4324-e4b2-11e7-98cf-f550a698f962.png)

**Comment by IFmiss** [comment]
换一个线上的地址试试，而且你这个报错是页面加载的时候出现的吗   还是你拖动调整之后  点击裁剪的时候的错，最好用线上的地址试一试

**Comment by ZhuRuiHeng** [comment]
我想自动给它一个裁剪框，它只能拖动不能改变裁剪框大小，这个怎么弄

**Comment by ZhuRuiHeng** [comment]
生成的图片是透明的

**Comment by IFmiss** [comment]
Duplicate of #3
