### ISSUE TITLE
微信小程序小白来提个问题

### ISSUE THREAD

**Issue by wjzhangcsu** [IFmiss/wx-cropper#7]
话说生成图片了，地址也打印出来了，但是怎么把图片存起来呢？或者怎么用那个图片的地址呢？我不能直接打开啊。是要在小程序里面才能打开那个地址吗？

**Comment by IFmiss** [comment]
我问了几个小伙伴，没有你说的这个问题，你可以将地址换到你们域名服务器提供的图片地址测试一下
