### ISSUE TITLE
真机上面 不能生成图片吗

### ISSUE THREAD

**Issue by Lanhaoo** [IFmiss/wx-cropper#9]
创建了一个测试工程，发现模拟器上面是可以生成的，真机上不能生成图片

**Comment by ljy0627** [comment]
是在生成图片的时候直接跳出了吗？我昨天也遇到类似问题，后来改了初始设置的DRAW_IMAGE_W值，他写的是10000，我改成1500，就可以了，你可以试试哦

**Comment by ljy0627** [comment]
> 创建了一个测试工程，发现模拟器上面是可以生成的，真机上不能生成图片

是在生成图片的时候直接跳出了吗？我昨天也遇到类似问题，后来改了初始设置的DRAW_IMAGE_W值，他写的是10000，我改成1500，就可以了，你可以试试哦
